project_name: "mgmt-research"
default_status: "To Do"
statuses: ["To Do", "Assessed", "Specified", "Planned", "In Implementation", "Validated", "Done"]
labels: []
milestones: []
date_format: yyyy-mm-dd
max_column_width: 20
auto_open_browser: true
default_port: 6420
remote_operations: false
auto_commit: false
zero_padded_ids: 3
bypass_git_hooks: true
check_active_branches: true
active_branch_days: 30
